resource:
  addr: http://localhost:8081/

oauth:
  resource: https://uaa.10.65.233.228.xip.io
  token: https://uaa.10.65.233.228.xip.io/oauth/token
  authorize: https://uaa.10.65.233.228.xip.io/oauth/authorize

security:
  basic:
    enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          client: DEBUG